# Generated by Django 5.0.3 on 2024-08-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langchain_stream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
